apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: food
bases:
  - ../dev
commonLabels:
  environment: tbe
resources:
  - sa.yaml
patchesStrategicMerge:
  - patch-deployment.yaml
configMapGenerator:
  - name: marketplace-finance-dashboard-configs
    behavior: merge
    envs:
      - .env
