apiVersion: apps/v1
kind: Deployment
metadata:
  labels: null
  name: marketplace-finance-dashboard
spec:
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: https://vault.tower.getirapi.com
        vault.security.banzaicloud.io/vault-path: kubernetes-eu-west-1-prod
        vault.security.banzaicloud.io/vault-role: prod-food-marketplace-finance-marketplace-finance-dashboard-role
    spec:
      containers:
        - env:
            - name: NEW_RELIC_LICENSE_KEY
              value: vault:kubernetes/data/global/new-relic#NEW_RELIC_LICENSE_KEY
            - name: RABBITMQ_URI
              value: amqps://${vault:rabbitmq/data/getir-aws/eu-west-1/payback-rabbitmq-broker/marketplace-finance-dashboard#username}:${vault:rabbitmq/data/getir-aws/eu-west-1/payback-rabbitmq-broker/marketplace-finance-dashboard#password}@b-a309adf6-4cd1-4283-a037-29f5078decf8.mq.eu-west-1.amazonaws.com:5671/marketplace-sap
            - name: MAIN_FOOD_MONGODB_URL
              value: mongodb+srv://${vault:mongodbatlas/static-creds/food-marketplace-finance-static-marketplace-finance-dashboard-marketplace-finance-sap-marketplace-finance-sap#username}:${vault:mongodbatlas/static-creds/food-marketplace-finance-static-marketplace-finance-dashboard-marketplace-finance-sap-marketplace-finance-sap#password}@marketplace-finance-sap.j5spa.mongodb.net/?readPreference=secondaryPreferred&w=majority&appName=marketplace-finance-dashboard-service
            - name: MAIN_LOCALS_MONGODB_URL
              value: mongodb+srv://${vault:mongodbatlas/static-creds/food-marketplace-finance-static-marketplace-finance-dashboard-marketplace-finance-sap-marketplace-finance-sap#username}:${vault:mongodbatlas/static-creds/food-marketplace-finance-static-marketplace-finance-dashboard-marketplace-finance-sap-marketplace-finance-sap#password}@marketplace-finance-sap.j5spa.mongodb.net/?readPreference=secondaryPreferred&w=majority&appName=marketplace-finance-dashboard-service
            - name: MAIN_WATER_MONGODB_URL
              value: mongodb+srv://${vault:mongodbatlas/static-creds/food-marketplace-finance-static-marketplace-finance-dashboard-marketplace-finance-sap-marketplace-finance-sap#username}:${vault:mongodbatlas/static-creds/food-marketplace-finance-static-marketplace-finance-dashboard-marketplace-finance-sap-marketplace-finance-sap#password}@marketplace-finance-sap.j5spa.mongodb.net/?readPreference=secondaryPreferred&w=majority&appName=marketplace-finance-dashboard-service
          image: 406421550649.dkr.ecr.eu-west-1.amazonaws.com/marketplace-finance-dashboard-service:v0.0.20
          name: marketplace-finance-dashboard
