apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: marketplace-finance-dashboard
spec:
  revisionHistoryLimit: 5
  selector:
    matchLabels:
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 10%
  template:
    metadata:
      labels:
      annotations:
        vault.security.banzaicloud.io/vault-skip-verify: "true"
    spec:
      containers:
        - image: 406421550649.dkr.ecr.eu-west-1.amazonaws.com/marketplace-finance-dashboard-service
          imagePullPolicy: Always
          name: marketplace-finance-dashboard
          envFrom:
            - configMapRef:
                name: marketplace-finance-dashboard-configs
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 250m
              memory: 500Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      imagePullSecrets:
        - name: regcred
      tolerations:
        - effect: NoSchedule
          key: getirapi.com/graviton-cpus
          operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: graviton
                    operator: In
                    values:
                      - "true"
                  - key: common
                    operator: In
                    values:
                      - "true"  
